### PR TITLE
Made changes to config files to build repyV1 runtime

### PR DESCRIPTION
**Pull request by choksi81**
Updated config files to build repvV1 runtime for nodemanager build.

### CODE REVIEW

**Comment by choksi81** [comment]
#112

**Comment by aaaaalbert** [comment]
Test results?

**Comment by choksi81** [comment]
For repyV1 runtime, results were:
```
Chintans-MacBook-Pro:runnable chintan$ grep -c 'PASS' result.txt 
155
Chintans-MacBook-Pro:runnable chintan$ grep -c 'FAIL' result.txt 
69
```
Many of the `Fails` were thrown by virtual_namespace.py. They were of type:
```
Full debugging traceback:
  "repy.py", line 448, in <module>
  "repy.py", line 179, in main
  "/Users/chintan/repy_v1/RUNNABLE/virtual_namespace.py", line 78, in __init__

User traceback:

Exception (with type 'exceptions.ValueError'): Code failed safety check! Error: ("<type 'exceptions.SyntaxError'> invalid syntax (line 12)",)
```

**Comment by aaaaalbert** [comment]
Have a go and dig into that problem! (Maybe there is a V1/V2 incompatibility with one of the runtime files?)

**Comment by choksi81** [comment]
The problem is with the emulcomm file. All the unit-tests where communication is done (i.e. emulcomm is used) are failing. Others are getting passed. 
If I remove emulcomm method from the unit-tests, they pass.

**Comment by aaaaalbert** [comment]
Let's make sure we are talking about the same issues here.

First, the init config needs to include `seattlelib_v1`, see above.

Second, I can't see any problems in the *nodemanager* unit tests that would relate to RepyV1 being included.

However, checking out SeattleTestbed/repy_v1, building, and running the unit tests causes lots of `SyntaxError`s. This is the problem that you mention. Take a look at any of the problematic source code lines --- you'll agree that we need to run `testportfiller` over the unit tests.

**Comment by aaaaalbert** [comment]
Instead of this PR, we chose an alternative implementation path: The RepyV1 directory is now included in SeattleTestbed/installer-packaging. It makes much more sense to include it there, because SeattleTestbed/nodemanager's build script can only build a nodemanager for testing anyway.

**Pull request closed without merging**
